// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2alsr1U4HWLT6p2PySJ8dBMcsFlBrrM',
    appId: '1:423242522130:web:2a94ff78a36798996b02cb',
    messagingSenderId: '423242522130',
    projectId: 'gbverse-product',
    authDomain: 'gbverse-product.firebaseapp.com',
    storageBucket: 'gbverse-product.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9w8BZRhwZu9GZFqlKTUjJ9me43zmbuAI',
    appId: '1:423242522130:android:61f5a5ccf6f0bc556b02cb',
    messagingSenderId: '423242522130',
    projectId: 'gbverse-product',
    storageBucket: 'gbverse-product.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5s0VcjwGe7_aVXjP_KTMWm1jFr3hxuM',
    appId: '1:423242522130:ios:7bdf219ab99065b66b02cb',
    messagingSenderId: '423242522130',
    projectId: 'gbverse-product',
    storageBucket: 'gbverse-product.appspot.com',
    iosClientId: '423242522130-jtee5tkdppq2pm17jbioo34coiroguke.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5s0VcjwGe7_aVXjP_KTMWm1jFr3hxuM',
    appId: '1:423242522130:ios:4fc23dbea5ec3c636b02cb',
    messagingSenderId: '423242522130',
    projectId: 'gbverse-product',
    storageBucket: 'gbverse-product.appspot.com',
    iosClientId: '423242522130-vi1kotfb2rprnrhva3rqrtn1ag2lsu6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbverse.RunnerTests',
  );
}
